/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import modelclasses.Staff;

/**
 *
 * @author CỌP
 */
public class ChangePassWord extends javax.swing.JPanel {

    /**
     * Creates new form ChangePassWord
     */
    public ChangePassWord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThayDoiMatKhau = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbHinhAnh = new javax.swing.JLabel();
        pnChuaChangePassword = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnChangePassword = new javax.swing.JPanel();
        lbMatKhauCu = new javax.swing.JLabel();
        lbMatKhauMoi = new javax.swing.JLabel();
        lbNhapLaiMatKhauMoi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        pwfMatKhauCu = new javax.swing.JPasswordField();
        pwfMatKhauMoi = new javax.swing.JPasswordField();
        pwfNhapLaiMatKhauMoi = new javax.swing.JPasswordField();

        pnThayDoiMatKhau.setBackground(new java.awt.Color(102, 102, 255));

        lbHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icondoimatkhau.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbHinhAnh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHinhAnh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnChuaChangePassword.setPreferredSize(new java.awt.Dimension(700, 450));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        pnChangePassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ChangePassWord\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        pnChangePassword.setForeground(new java.awt.Color(0, 0, 255));

        lbMatKhauCu.setText("Mật khẩu cũ");

        lbMatKhauMoi.setText("Mật khẩu mới");

        lbNhapLaiMatKhauMoi.setText("Nhập lại mật khẩu mới");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Quay lại");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnXacNhan)
                .addGap(18, 18, 18)
                .addComponent(btnHuy)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnChangePasswordLayout = new javax.swing.GroupLayout(pnChangePassword);
        pnChangePassword.setLayout(pnChangePasswordLayout);
        pnChangePasswordLayout.setHorizontalGroup(
            pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMatKhauCu)
                    .addComponent(lbNhapLaiMatKhauMoi)
                    .addComponent(lbMatKhauMoi))
                .addGap(66, 66, 66)
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwfMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(pwfMatKhauMoi)
                    .addComponent(pwfNhapLaiMatKhauMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnChangePasswordLayout.setVerticalGroup(
            pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChangePasswordLayout.createSequentialGroup()
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChangePasswordLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbMatKhauCu))
                    .addGroup(pnChangePasswordLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(pwfMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMatKhauMoi)
                    .addComponent(pwfMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNhapLaiMatKhauMoi)
                    .addComponent(pwfNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout pnChuaChangePasswordLayout = new javax.swing.GroupLayout(pnChuaChangePassword);
        pnChuaChangePassword.setLayout(pnChuaChangePasswordLayout);
        pnChuaChangePasswordLayout.setHorizontalGroup(
            pnChuaChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChuaChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnChuaChangePasswordLayout.setVerticalGroup(
            pnChuaChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChuaChangePasswordLayout.createSequentialGroup()
                .addGroup(pnChuaChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnChuaChangePasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnChuaChangePasswordLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnThayDoiMatKhauLayout = new javax.swing.GroupLayout(pnThayDoiMatKhau);
        pnThayDoiMatKhau.setLayout(pnThayDoiMatKhauLayout);
        pnThayDoiMatKhauLayout.setHorizontalGroup(
            pnThayDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThayDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(pnChuaChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnThayDoiMatKhauLayout.setVerticalGroup(
            pnThayDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThayDoiMatKhauLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThayDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnChuaChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThayDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThayDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure comeback", "Back", 2) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        try {
            Staff st = Home.staff;
            String a = String.valueOf(this.pwfMatKhauCu.getPassword());
            if (st.getpW().equalsIgnoreCase(a)) {
                Staff st1 = new Staff();
                st1.ChangePassword(st.getMaNV(), String.valueOf(this.pwfNhapLaiMatKhauMoi.getPassword()));
                JOptionPane.showMessageDialog(this, "Change password success!");
            } else {
                JOptionPane.showMessageDialog(this, "Change password faild, please check again!", "Message", 2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Check again, please", "Message", 2);
        }

    }//GEN-LAST:event_btnXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbMatKhauCu;
    private javax.swing.JLabel lbMatKhauMoi;
    private javax.swing.JLabel lbNhapLaiMatKhauMoi;
    private javax.swing.JPanel pnChangePassword;
    private javax.swing.JPanel pnChuaChangePassword;
    private javax.swing.JPanel pnThayDoiMatKhau;
    private javax.swing.JPasswordField pwfMatKhauCu;
    private javax.swing.JPasswordField pwfMatKhauMoi;
    private javax.swing.JPasswordField pwfNhapLaiMatKhauMoi;
    // End of variables declaration//GEN-END:variables
}
