package gui;

import javax.swing.JOptionPane;
import modelclasses.Staff;

/**
 *
 * @author CỌP
 */
public class Home extends javax.swing.JFrame {

    // class use chung, nó không tuân theo từng lớp cụ thể nào cả.
    public static Staff staff;

    public Home() {
        initComponents();
        this.setSize(901, 599);//[901, 599]
        setResizable(false);
        pack();
        HomeImage tc2 = new HomeImage();
        pnNoiDung.setBottomComponent(tc2);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNoiDung = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnHeThong = new javax.swing.JMenu();
        mnitTrangChu = new javax.swing.JMenuItem();
        mnitDangNhap = new javax.swing.JMenuItem();
        mnitDangKyTaiKhoan = new javax.swing.JMenuItem();
        mnitDoiMatKhau = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnitThoat = new javax.swing.JMenuItem();
        mnTacNghiep = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        GhiNhatKyMenuITem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mniXemNhatKyCuaMotNhanVien = new javax.swing.JMenuItem();
        mnTroGiup = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Sự - Cọp");
        setBackground(new java.awt.Color(102, 102, 255));

        pnNoiDung.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        pnNoiDung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnNoiDung.setMinimumSize(new java.awt.Dimension(91, 83));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconqlns.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN SỰ ");
        pnNoiDung.setLeftComponent(jLabel1);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pnNoiDung.setRightComponent(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 255));

        mnHeThong.setText("Hệ thống");

        mnitTrangChu.setText("Trang chủ");
        mnitTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitTrangChuActionPerformed(evt);
            }
        });
        mnHeThong.add(mnitTrangChu);

        mnitDangNhap.setText("Đăng nhập");
        mnitDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitDangNhapActionPerformed(evt);
            }
        });
        mnHeThong.add(mnitDangNhap);

        mnitDangKyTaiKhoan.setText("Đăng ký tài khoản");
        mnitDangKyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitDangKyTaiKhoanActionPerformed(evt);
            }
        });
        mnHeThong.add(mnitDangKyTaiKhoan);

        mnitDoiMatKhau.setText("Đổi mật khẩu");
        mnitDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitDoiMatKhauActionPerformed(evt);
            }
        });
        mnHeThong.add(mnitDoiMatKhau);

        jMenuItem3.setText("Chỉnh sửa thông tin cá nhân");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnHeThong.add(jMenuItem3);

        jMenuItem6.setText("Đăng xuất");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnHeThong.add(jMenuItem6);

        mnitThoat.setText("Thoát");
        mnitThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitThoatActionPerformed(evt);
            }
        });
        mnHeThong.add(mnitThoat);

        jMenuBar1.add(mnHeThong);

        mnTacNghiep.setText("Tác nghiệp");

        jMenuItem4.setText("Thêm một nhật viên mới");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnTacNghiep.add(jMenuItem4);

        GhiNhatKyMenuITem.setText("Ghi nhật ký sự kiện");
        GhiNhatKyMenuITem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GhiNhatKyMenuITemActionPerformed(evt);
            }
        });
        mnTacNghiep.add(GhiNhatKyMenuITem);

        jMenuItem1.setText("Xem danh sách nhân viên trong đơn vị");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnTacNghiep.add(jMenuItem1);

        mniXemNhatKyCuaMotNhanVien.setText("Xem nhật ký của một nhân viên");
        mniXemNhatKyCuaMotNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXemNhatKyCuaMotNhanVienActionPerformed(evt);
            }
        });
        mnTacNghiep.add(mniXemNhatKyCuaMotNhanVien);

        jMenuBar1.add(mnTacNghiep);

        mnTroGiup.setText("Trợ giúp");

        jMenuItem2.setText("Suport Image");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnTroGiup.add(jMenuItem2);

        jMenuBar1.add(mnTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNoiDung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitDangNhapActionPerformed
        Login lp = new Login();
        this.pnNoiDung.setBottomComponent(lp);
        pack();
    }//GEN-LAST:event_mnitDangNhapActionPerformed

    private void GhiNhatKyMenuITemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GhiNhatKyMenuITemActionPerformed
        // TODO add your handling code here:
        if (staff != null) {
            WriteStaffTransLog nkns = new WriteStaffTransLog();
            pnNoiDung.setBottomComponent(nkns);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập rồi mới ghi nhật ký!", "", 1);
        }
    }//GEN-LAST:event_GhiNhatKyMenuITemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:        
        if (staff != null) {
            SeeStaffListAnyDepartmant lp1 = new SeeStaffListAnyDepartmant();
            pnNoiDung.setBottomComponent(lp1);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập mới được xem danh sách nhân viên, xin cảm ơn!", "", 1);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnitTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitTrangChuActionPerformed

        HomeImage tc2 = new HomeImage();
        pnNoiDung.setBottomComponent(tc2);
        pack();
    }//GEN-LAST:event_mnitTrangChuActionPerformed

    private void mnitThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnitThoatActionPerformed

    private void mnitDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitDoiMatKhauActionPerformed

        if (staff != null) {
            ChangePassWord cpw1 = new ChangePassWord();
            this.pnNoiDung.setBottomComponent(cpw1);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập rồi mới đổi mật khẩu!", "", 1);
        }

    }//GEN-LAST:event_mnitDoiMatKhauActionPerformed

    private void mniXemNhatKyCuaMotNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXemNhatKyCuaMotNhanVienActionPerformed

        if (staff != null) {
            SeeTranslogOfTheStaff tc2 = new SeeTranslogOfTheStaff();
            this.pnNoiDung.setBottomComponent(tc2);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập rồi mới xem nhật ký!", "", 1);
        }
    }//GEN-LAST:event_mniXemNhatKyCuaMotNhanVienActionPerformed

    private void mnitDangKyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitDangKyTaiKhoanActionPerformed
        CreateAnAccount isastnac = new CreateAnAccount();
        this.pnNoiDung.setBottomComponent(isastnac);
        pack();
    }//GEN-LAST:event_mnitDangKyTaiKhoanActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Suport sp = new Suport();
        pnNoiDung.setBottomComponent(sp);
        pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        if (staff != null) {
            UpdateInfo cstt = new UpdateInfo();
            pnNoiDung.setBottomComponent(cstt);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập rồi mới chỉnh sửa thông tin!", "", 1);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (staff != null) {
            staff = null;
            HomeImage sp = new HomeImage();
            pnNoiDung.setBottomComponent(sp);
            pack();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (staff != null) {
            InsertStaffIntoStaffandDSNVi cstt = new InsertStaffIntoStaffandDSNVi();
            pnNoiDung.setBottomComponent(cstt);
            pack();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập rồi mới thêm nhân viên mới!", "", 1);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GhiNhatKyMenuITem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenu mnTacNghiep;
    private javax.swing.JMenu mnTroGiup;
    private javax.swing.JMenuItem mniXemNhatKyCuaMotNhanVien;
    private javax.swing.JMenuItem mnitDangKyTaiKhoan;
    private javax.swing.JMenuItem mnitDangNhap;
    private javax.swing.JMenuItem mnitDoiMatKhau;
    private javax.swing.JMenuItem mnitThoat;
    private javax.swing.JMenuItem mnitTrangChu;
    private javax.swing.JSplitPane pnNoiDung;
    // End of variables declaration//GEN-END:variables
}
