package gui;
import static gui.Home.staff;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelclasses.Staff;
import modelclasses.Staff;

/**
 *
 * @author CỌP
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage
     */
    public Login() {
        initComponents();
        this.setSize(879, 491);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DangNhapPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manvtxt = new java.awt.TextField();
        dangnhapbt = new javax.swing.JButton();
        btmHuy = new javax.swing.JButton();
        passwordtxt = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(789, 491));

        DangNhapPane.setBackground(new java.awt.Color(255, 255, 255));
        DangNhapPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đăng nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        DangNhapPane.setForeground(new java.awt.Color(0, 0, 204));
        DangNhapPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("ID:");

        jLabel3.setText("Password:");

        manvtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manvtxtActionPerformed(evt);
            }
        });

        dangnhapbt.setBackground(new java.awt.Color(102, 102, 255));
        dangnhapbt.setText("Đăng Nhập");
        dangnhapbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapbtActionPerformed(evt);
            }
        });

        btmHuy.setText("Hủy");
        btmHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmHuyActionPerformed(evt);
            }
        });

        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        passwordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordtxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout DangNhapPaneLayout = new javax.swing.GroupLayout(DangNhapPane);
        DangNhapPane.setLayout(DangNhapPaneLayout);
        DangNhapPaneLayout.setHorizontalGroup(
            DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapPaneLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(81, 81, 81)
                .addGroup(DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DangNhapPaneLayout.createSequentialGroup()
                        .addComponent(dangnhapbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manvtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(passwordtxt))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        DangNhapPaneLayout.setVerticalGroup(
            DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapPaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(manvtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(DangNhapPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangnhapbt)
                    .addComponent(btmHuy))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(DangNhapPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(DangNhapPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        DangNhapPane.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void manvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manvtxtActionPerformed

    private void dangnhapbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapbtActionPerformed
        try {
            String manv = manvtxt.getText();
            int manvchinh = Integer.parseInt(manv);
            String matkhau = passwordtxt.getText();
            Home.staff = new Staff().Login(manvchinh, matkhau);
            if (staff != null) {
                JOptionPane.showMessageDialog(this, "Login Success, Hello: " + staff.getHo() + " " + staff.getTen());
            } else {
                JOptionPane.showMessageDialog(this, "Login Faild");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra và đăng nhập lại, xin cám ơn", "Message", 1);
        }


    }//GEN-LAST:event_dangnhapbtActionPerformed

    private void btmHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmHuyActionPerformed
        // TODO add your handling code here:      
        btmHuy.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int click = JOptionPane.showConfirmDialog(null, "Are you sure exit this GUI !", "Question", JOptionPane.YES_NO_OPTION);
                System.exit(0);
            }
        });

    }//GEN-LAST:event_btmHuyActionPerformed

    private void passwordtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Enter was pressed. Your code goes here.
            try {
                String manv = manvtxt.getText();
                int manvchinh = Integer.parseInt(manv);
                String matkhau = passwordtxt.getText();
                Home.staff = new Staff().Login(manvchinh, matkhau);
                if (staff != null) {
                    JOptionPane.showMessageDialog(this, "Login Success, Hello: " + staff.getHo() + " " + staff.getTen());
                } else {
                    JOptionPane.showMessageDialog(this, "Login Faild");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra và đăng nhập lại, xin cám ơn", "Message", 1);
            }
        }
    }//GEN-LAST:event_passwordtxtKeyPressed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangNhapPane;
    private javax.swing.JButton btmHuy;
    private javax.swing.JButton dangnhapbt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.TextField manvtxt;
    private javax.swing.JPasswordField passwordtxt;
    // End of variables declaration//GEN-END:variables
}
